# EXAMPLE OF A CONFIG

#This needs to be a string stating with :
port: ":8080"
release_mode: "release" #switch to "release" in prod
#keep debug for testing
frontend: "http://localhost:8080" #Your frontend path(for OAuth)
# It is important that this url and your APIs match.
# ex: backend:  http://yourdomain/user/profile
# ex: frontend: http://yourdomain/user/profile
# if they don't match, well, don't expect things to work...

db:
  max_cons: 4 #Max simultaneous cons
  min_cons: 1 #Min cons active
  min_idle_cons: 1 #Min cons that are idle
  health_check_period: "1m"
  max_con_lifetime: "5m"
  max_con_lifetime_jitter: "1m"
  max_con_idle_time: "3m"
  ctx_timeout: "15s" #Max time waiting for a call to the db

redis:
  ctx_timeout: "15s"
  margin_time: "1m"
  addr: "auth_redis:6379"

#Standar CORS settings, prety self explicatory
cors:
  allow_all_origins: false
  allow_private_network: false
  allow_credentials: true
  allow_wildcard: false
  allow_browser_extensions: false
  allow_websockets: false
  allow_files: false
  allow_origins:
    - "http://localhost:8080"
    # IMPORTANT: this must match your frontend
  allow_methods:
    - "GET"
    - "POST"
  allow_headers:
    - "Authorization"
    - "Content-Type"
  max_age: "12h"
  options_response_status: 204

#Standar JWT settings
jwt:
  realm: "Backend API"
  timeout: "15m"
  max_refresh: "8h"
  token_lookup: "header: Authorization, query: token, cookie: access_token"
  token_head_name: "Bearer"
  cookie_name: "access_token"
  send_cookie: true
  secure_cookie: true
  cookie_same_site: 4  # 1=Default 2=Lax 3=Strict 4=None
  cookie_http_only: true
  cookie_max_age: "15m"
  cookie_domain: ""
  send_authorization: true

#Oauth paths, atm is hard coded, but change the paths to this
# https://accounts.google.com/.well-known/openid-configuration
# usefull data for setting google
oauth:
  provider: "https://accounts.google.com/o/oauth2/auth"
  token_provider: "https://oauth2.googleapis.com/token"
  redirect_uri: "http://localhost:8080/OAuthCallback"
  issuer_url: "https://accounts.google.com"
  jwks: "https://www.googleapis.com/oauth2/v3/certs"


#Amount of request per IP + PATH and when to update them.
rate:
  max_request: 500
  reset_interval: 2m
  refill: 100

logger:
  path: "tmp/test.log" #Path where the file is located
  level: "info" #Which level would be filtrated, levels = debug, info, warn, error
  max_size: 200 #Size in MB
  max_age: 7 #Numbers of days in storage
  max_backups: 4 #Number of backups allowed
  local_time: true #False = UTC, true = machine zone.
  compress: false #If this should compress the logs
  source: true #DEBUG info for leaving the entrypoint for a logging action

#Mail, quite simple, add a provider, and the mail that would send the emails
mail:
  provider: "smtp.mailgun.org"
  user: "MailTest@sandbox3559960e87ba466eb56a024ece83cb47.mailgun.org"
  from: "MailTest@sandbox3559960e87ba466eb56a024ece83cb47.mailgun.org"
  port: 587
  queue_size: 10000
  max_workers: 4
  min_workers: 1
  worker_per_queue: 200
  sleep_time: 2m

delete:
  #Time d is not well parsed, converted into hours.
  delete_time: 168h

password:
  #Password based on min entropy needed, that means that you are setting how hard would be to break the password,
  # Between 50-70 is average, 80 is recomended.
  #rather than if it contains a mayus, or a @# sign, or similars.
  # More info: https://pkg.go.dev/github.com/wagslane/go-password-validator#section-readme
  min_entropy: 80.0
